// Generated by CoffeeScript 1.3.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(['underscore', 'backbone'], function(_, Backbone) {
    var Model;
    return Model = (function(_super) {

      __extends(Model, _super);

      function Model() {
        return Model.__super__.constructor.apply(this, arguments);
      }

      Model.prototype.defaults = {
        crumbs: [],
        projectName: 'anonProject'
      };

      Model.prototype.path = function(path) {
        var inits, segment, segments, _i, _len;
        segments = _.compact(path.split('/'));
        inits = [''];
        for (_i = 0, _len = segments.length; _i < _len; _i++) {
          segment = segments[_i];
          inits.push(_.last(inits) + segment + '/');
        }
        inits = _.tail(inits);
        inits = _(inits).map(function(e, i) {
          return {
            segment: e,
            pathname: segments[i]
          };
        });
        return this.set('crumbs', inits);
      };

      return Model;

    })(Backbone.Model);
  });

}).call(this);
