// Generated by CoffeeScript 1.3.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(['jquery', 'underscore', 'backbone', 'template', 'router', 'model'], function($, _, Backbone, template, router, model) {
    var Breadcrumb;
    return Breadcrumb = (function(_super) {

      __extends(Breadcrumb, _super);

      function Breadcrumb() {
        return Breadcrumb.__super__.constructor.apply(this, arguments);
      }

      Breadcrumb.prototype.el = $('#breadcrumb');

      Breadcrumb.prototype.initialize = function() {
        var _this = this;
        this.template = template.breadcrumb;
        this.model = new model.Breadcrumb;
        router.on('route:home', function() {
          return _this.$el.fadeOut(100).hide().html(_this.template.render({
            paths: _this.model.home()
          })).fadeIn(500);
        });
        return router.on('route:prodject', function(name) {
          return _this.$el.fadeOut(100).hide().html(_this.template.render({
            paths: _this.model.project(name)
          })).fadeIn(500);
        });
      };

      return Breadcrumb;

    })(Backbone.View);
  });

}).call(this);
