// Generated by CoffeeScript 1.3.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(['jquery', 'underscore', 'backbone', 'hogan', 'router'], function($, _, Backbone, hogan, router) {
    var Breadcrumb;
    return Breadcrumb = (function(_super) {

      __extends(Breadcrumb, _super);

      function Breadcrumb() {
        return Breadcrumb.__super__.constructor.apply(this, arguments);
      }

      Breadcrumb.prototype.initialize = function() {
        router.on('route:projectList', function() {
          return console.log('fuck');
        });
        router.on('route:project', function(id) {
          return console.log('fuck', id);
        });
        return router.on('route:anything', function() {
          return console.log('not found');
        });
      };

      return Breadcrumb;

    })(Backbone.View);
  });

}).call(this);
