// Generated by CoffeeScript 1.3.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(['jquery', 'underscore', 'backbone', 'hogan', 'template', 'model'], function($, _, Backbone, hogan, template, MODEL) {
    var File;
    return File = (function(_super) {

      __extends(File, _super);

      function File() {
        return File.__super__.constructor.apply(this, arguments);
      }

      File.prototype.el = $('#main');

      File.prototype.initialize = function() {
        this.template = template.file;
        return this.projects = new MODEL.Projects;
      };

      File.prototype.render = function(name) {
        var _this = this;
        this.projects.hol(function() {
          var files, pid;
          pid = _this.projects.where({
            name: name
          })[0].id;
          console.log(pid);
          files = new MODEL.Files({
            pid: pid
          });
          return $.get("projects/" + pid + "/files.json", function(reply) {
            return _this.$el.html(_this.template.render({
              test: JSON.stringify(reply)
            }));
          });
        });
        return this;
      };

      return File;

    })(Backbone.View);
  });

}).call(this);
