// Generated by CoffeeScript 1.4.0
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(['jquery', 'backbone', 'template', 'backbone.marionette'], function($, Backbone, $$) {
    var File;
    return File = (function(_super) {

      __extends(File, _super);

      function File() {
        return File.__super__.constructor.apply(this, arguments);
      }

      File.prototype.tagName = 'li';

      File.prototype["class"] = 'file';

      File.prototype.template = $$.file;

      return File;

    })(Backbone.Marionette.ItemView);
  });

}).call(this);
