// Generated by CoffeeScript 1.3.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(['jquery', 'underscore', 'backbone', 'hogan', 'template', 'model'], function($, _, Backbone, hogan, template, model) {
    var Locale;
    return Locale = (function(_super) {

      __extends(Locale, _super);

      function Locale() {
        return Locale.__super__.constructor.apply(this, arguments);
      }

      Locale.prototype.el = '#locales';

      Locale.prototype.initialize = function() {
        return this.template = template.locale;
      };

      Locale.prototype.render = function(id, pname, callback) {
        var _this = this;
        this.collection = new model.Locales({
          id: id
        });
        this.collection.snatch(function() {
          var json;
          json = _this.collection.map(function(n) {
            return n.set('pname', pname);
          }).map(function(model) {
            return model.toJSON();
          });
          return callback(_this.template.render({
            locales: json
          }));
        });
        return this;
      };

      return Locale;

    })(Backbone.View);
  });

}).call(this);
