// Generated by CoffeeScript 1.3.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(['jquery', 'underscore', 'backbone', 'hogan', 'template', 'model'], function($, _, Backbone, hogan, template, model) {
    var Project;
    return Project = (function(_super) {

      __extends(Project, _super);

      function Project() {
        return Project.__super__.constructor.apply(this, arguments);
      }

      Project.prototype.el = $('#main');

      Project.prototype.initialize = function(name) {
        this.template = hogan.compile(template.project);
        return this.model = new model.Project;
      };

      Project.prototype.render = function() {
        var _this = this;
        return this.collection.on('reset', function() {
          return _this.$el.html(_this.template.render({
            projects: _this.collection.toJSON()
          }));
        });
      };

      return Project;

    })(Backbone.View);
  });

}).call(this);
