// Generated by CoffeeScript 1.3.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(['jquery', 'underscore', 'backbone', 'hogan', 'template', 'model'], function($, _, Backbone, hogan, template, MODEL) {
    var Project;
    return Project = (function(_super) {

      __extends(Project, _super);

      function Project() {
        return Project.__super__.constructor.apply(this, arguments);
      }

      Project.prototype.el = $('#main');

      Project.prototype.initialize = function() {
        this.template = template.project;
        return this.collection = new MODEL.Projects;
      };

      Project.prototype.render = function(name) {
        var _this = this;
        this.collection.snatch(function() {
          var model;
          console.log(name);
          model = _this.collection.where({
            name: name
          })[0];
          return _this.$el.html(_this.template.render({
            name: model.get('name'),
            info: model.get('info'),
            id: model.id
          }));
        });
        return this;
      };

      return Project;

    })(Backbone.View);
  });

}).call(this);
