// Generated by CoffeeScript 1.3.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(['jquery', 'underscore', 'backbone', 'hogan', 'template', 'model'], function($, _, Backbone, hogan, template, MODEL) {
    var ProjectBreadcrumb;
    return ProjectBreadcrumb = (function(_super) {

      __extends(ProjectBreadcrumb, _super);

      function ProjectBreadcrumb() {
        return ProjectBreadcrumb.__super__.constructor.apply(this, arguments);
      }

      ProjectBreadcrumb.prototype.tagName = 'ol';

      ProjectBreadcrumb.prototype.initialize = function() {
        var _this = this;
        return this.model.on('change', function() {
          return _this.render();
        });
      };

      ProjectBreadcrumb.prototype.render = function() {
        this.template = template.projectBreadcrumb;
        this.$el.html(this.template.render({
          projectName: this.model.get('projectName'),
          crumbs: this.model.get('crumbs')
        }));
        console.log(this.$el);
        return this;
      };

      return ProjectBreadcrumb;

    })(Backbone.View);
  });

}).call(this);
