// Generated by CoffeeScript 1.4.0
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(['jquery', 'backbone', 'template'], function($, Backbone, $$) {
    var Registration;
    return Registration = (function(_super) {

      __extends(Registration, _super);

      function Registration() {
        return Registration.__super__.constructor.apply(this, arguments);
      }

      Registration.prototype.tagName = 'article';

      Registration.prototype.id = 'registration';

      Registration.prototype.template = $$.registration;

      Registration.prototype.initialize = function() {
        return this.render();
      };

      Registration.prototype.render = function() {
        this.$el.html(this.template.render());
        return this;
      };

      return Registration;

    })(Backbone.View);
  });

}).call(this);
