// Generated by CoffeeScript 1.4.0
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(['backbone'], function(Backbone) {
    var Project;
    return Project = (function(_super) {

      __extends(Project, _super);

      function Project() {
        return Project.__super__.constructor.apply(this, arguments);
      }

      Project.prototype.url = function() {
        return "/api/projects/" + this.id;
      };

      Project.prototype.parse = function(data) {
        return {
          name: data.name,
          info: data.info,
          id: data.id,
          fileType: data.file_type,
          isEmpty: data.num_of_entries === 0,
          numberOfEntries: data.num_of_entries,
          numberOfUnpickedEntries: data.num_of_unpicked_entries,
          numberOfUntranslatedEntries: data.num_of_untranslated_entries,
          locales: data.project_locales,
          tags: data.tags
        };
      };

      return Project;

    })(Backbone.Model);
  });

}).call(this);
