// Generated by CoffeeScript 1.4.0
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(['collections/entry', 'collections/locale', 'collections/localetree', 'models/project/browser', 'views/entry', 'jquery', 'backbone', 'template'], function(CollectionEntry, CollectionLocale, CollectionLocaletree, ModelProjectBrowser, ViewEntry, $, Backbone, $$) {
    var FileBrowser;
    return FileBrowser = (function(_super) {

      __extends(FileBrowser, _super);

      function FileBrowser() {
        return FileBrowser.__super__.constructor.apply(this, arguments);
      }

      FileBrowser.prototype.tagName = 'ol';

      FileBrowser.prototype.initialize = function() {
        var _this = this;
        this.collection.on('reset', function() {
          return _this.render();
        });
        this.model = new ModelProjectBrowser;
        this.view = {
          Entries: ViewEntry
        };
        return this.listenTo(Backbone.settings, 'change:fileOrdering', this.eventFileOrdering);
      };

      FileBrowser.prototype.eventFileOrdering = function() {
        var ordering;
        ordering = Backbone.settings.get('fileOrdering');
        switch (ordering) {
          case 'list':
            return this.$el.removeClass('icon-ordering').addClass('list-ordering');
          case 'icon':
            return this.$el.removeClass('list-ordering').addClass('icon-ordering');
        }
      };

      FileBrowser.prototype.render = function() {
        var fileID, isFile, locales, projectID, template, _ref,
          _this = this;
        template = $$.projectBrowser;
        isFile = ((_ref = this.collection.node()) != null ? _ref.folder : void 0) === false;
        projectID = this.collection.id;
        fileID = this.collection.node();
        if (isFile) {
          locales = new CollectionLocale;
          locales.id = projectID;
          locales.snatch(function() {
            var localeTree, projectLocaleID, _ref1;
            projectLocaleID = (_ref1 = locales.where({
              localeID: 1
            })) != null ? _ref1[0].get('id') : void 0;
            localeTree = new CollectionLocaletree;
            localeTree.id = projectLocaleID;
            return localeTree.snatch(function() {
              var entries, entriesView, projectFileID, _ref2;
              projectFileID = _this.collection.node().id;
              fileID = (_ref2 = localeTree.where({
                'project_file_id': projectFileID
              })) != null ? _ref2[0].get('id') : void 0;
              entries = new CollectionEntry;
              entries.id = fileID;
              entriesView = new ViewEntry({
                collection: entries
              });
              _this.assign(entriesView, '#project-file');
              return entries.snatch();
            });
          });
        } else {
          this.$el.html(template.render({
            isFile: isFile,
            files: this.collection.children(),
            root: this.collection.root(),
            projectName: this.collection.name
          }));
          this.eventFileOrdering();
        }
        return this;
      };

      return FileBrowser;

    })(Backbone.View);
  });

}).call(this);
