// Generated by CoffeeScript 1.4.0
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(['collections/project', 'jquery', 'backbone', 'template'], function(CollectionProject, $, Backbone, $$) {
    var ProjectList;
    return ProjectList = (function(_super) {

      __extends(ProjectList, _super);

      function ProjectList() {
        return ProjectList.__super__.constructor.apply(this, arguments);
      }

      ProjectList.prototype.el = $('#main');

      ProjectList.prototype.render = function() {
        var projects,
          _this = this;
        projects = new CollectionProject;
        projects.snatch(function() {
          return _this.$el.html($$.projectList.render({
            projects: projects.toJSON()
          }));
        });
        return this;
      };

      return ProjectList;

    })(Backbone.View);
  });

}).call(this);
