// Generated by CoffeeScript 1.4.0
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(['jquery', 'backbone', 'template', 'backbone.marionette'], function($, Backbone, $$) {
    var ProjectListItem;
    return ProjectListItem = (function(_super) {

      __extends(ProjectListItem, _super);

      function ProjectListItem() {
        return ProjectListItem.__super__.constructor.apply(this, arguments);
      }

      ProjectListItem.prototype.tagName = 'li';

      ProjectListItem.prototype.className = 'project-list-item';

      ProjectListItem.prototype.template = $$.projectListitem;

      return ProjectListItem;

    })(Backbone.Marionette.ItemView);
  });

}).call(this);
