// Generated by CoffeeScript 1.3.3
(function() {

  define(['collections/entry', 'collections/entrylist', 'collections/filetree', 'collections/locale', 'collections/localetree', 'collections/project'], function(Entry, Entrylist, Filetree, Locale, Localetree, Project) {
    return {
      Entry: Entry,
      Entrylist: Entrylist,
      Filetree: Filetree,
      Locale: Locale,
      Localetree: Localetree,
      Project: Project
    };
  });

}).call(this);
