// Generated by CoffeeScript 1.3.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  require.config({
    paths: {
      jquery: 'jam/jquery/jquery',
      underscore: 'jam/underscore/underscore',
      backbone: 'jam/backbone/backbone',
      hogan: 'jam/hogan/hogan',
      router: 'router',
      model: 'model',
      template: 'template'
    }
  });

  require(['jquery', 'underscore', 'backbone', 'hogan', 'router', 'views/home', 'views/project', 'views/breadcrumb'], function($, _, Backbone, hogan, router, Home, Project, Breadcrumb) {
    var App;
    App = (function(_super) {

      __extends(App, _super);

      function App() {
        return App.__super__.constructor.apply(this, arguments);
      }

      App.prototype.el = $(window);

      App.prototype.events = {
        'scroll': 'scroll'
      };

      App.prototype.initialize = function() {};

      App.prototype.scroll = function() {
        var scrollTop;
        scrollTop = this.$el.scrollTop();
        if (scrollTop > 60) {
          $('#breadcrumb-container').addClass('fixed');
          return $('#main-container').addClass('fixed');
        } else {
          $('#breadcrumb-container').removeClass('fixed');
          return $('#main-container').removeClass('fixed');
        }
      };

      return App;

    })(Backbone.View);
    return $(function() {
      new App;
      new Breadcrumb;
      router.on('route:project', function(id) {
        var project;
        project = new Project;
        return project.render();
      });
      router.on('route:home', function() {
        var homePage;
        homePage = new Home;
        return homePage.render();
      });
      return Backbone.history.start();
    });
  });

}).call(this);
