// Generated by CoffeeScript 1.3.3
(function() {

  define(['models/filebrowser', 'models/project/breadcrumb', 'models/project'], function(Filebrowser, ProjectBreadcrumb, Project) {
    return {
      Filebrowser: Filebrowser,
      ProjectBreadcrumb: ProjectBreadcrumb,
      Project: Project
    };
  });

}).call(this);
