// Generated by CoffeeScript 1.3.3
(function() {

  define(['models/project', 'collections/project', 'models/locale', 'collections/locale', 'models/breadcrumb'], function(Project, Projects, Locale, Locales, Breadcrumb) {
    return {
      Project: Project,
      Projects: Projects,
      Locale: Locale,
      Locales: Locales,
      Breadcrumb: Breadcrumb
    };
  });

}).call(this);
