// Generated by CoffeeScript 1.3.3
(function() {

  define(['models/project', 'collections/project'], function(Project, Projects) {
    return {
      Project: Project,
      Projects: Projects
    };
  });

}).call(this);
