// Generated by CoffeeScript 1.4.0
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(['views/home', 'views/project/list', 'jquery', 'backbone'], function(ViewHome, ViewProjectList, $, Backbone) {
    var Router;
    Router = (function(_super) {

      __extends(Router, _super);

      function Router() {
        return Router.__super__.constructor.apply(this, arguments);
      }

      Router.prototype.routes = {
        '': 'home',
        'project': 'project'
      };

      Router.prototype.home = function() {
        var homeView;
        homeView = new ViewHome;
        return $('body').html(homeView.render());
      };

      Router.prototype.project = function() {
        var projectListView;
        projectListView = new ViewProjectList;
        return $('body').html(projectListView.render());
      };

      return Router;

    })(Backbone.Router);
    return new Router;
  });

}).call(this);
