// Generated by CoffeeScript 1.4.0
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(['views/api', 'views/notfound', 'views/project/list', 'views/project', 'views/registration', 'views/settings', 'jquery', 'backbone'], function(ViewApi, ViewNotfound, ViewProjectList, ViewProject, ViewRegistration, ViewSettings, $, Backbone) {
    var Router;
    return new (Router = (function(_super) {

      __extends(Router, _super);

      function Router() {
        return Router.__super__.constructor.apply(this, arguments);
      }

      Router.prototype.routes = {
        '': 'home',
        'registration': 'registration',
        'settings': 'settings',
        'project': 'project',
        'project/:name/file': 'project:file',
        'project/:name/file/*path': 'project:file',
        'api_reference': 'api',
        '*all': 'otherwise'
      };

      Router.prototype['registration'] = function() {
        var registrationPage;
        registrationPage = new ViewRegistration;
        return registrationPage.render();
      };

      Router.prototype['settings'] = function() {
        var settingsPage;
        settingsPage = new ViewSettings;
        return settingsPage.render();
      };

      Router.prototype['project'] = function() {
        var projectList;
        projectList = new ViewProjectList;
        return projectList.render();
      };

      Router.prototype['project:file'] = function(name, path) {
        var project;
        project = new ViewProject;
        if (path != null) {
          path = path.replace(/\/$/, '');
        } else {
          path = '';
        }
        return project.render(name, path);
      };

      Router.prototype['api'] = function() {
        var api;
        api = new ViewApi;
        return api.render();
      };

      Router.prototype['otherwise'] = function(path) {
        var notFound;
        notFound = new ViewNotfound;
        return notFound.render(path);
      };

      return Router;

    })(Backbone.Router));
  });

}).call(this);
