// Generated by CoffeeScript 1.4.0
(function() {

  define(['storage', 'jquery', 'underscore', 'backbone'], function(Storage, $, _, Backbone) {
    Backbone.remoteSync = Backbone.sync;
    Backbone.sync = function() {
      Backbone.remoteSync.apply(this, arguments);
      return Storage.apply(this, arguments);
    };
    Backbone.Model.prototype.snatch = function(callback, args) {
      var parameters;
      if (callback != null) {
        this.once('change', callback);
      }
      if (!(args != null)) {
        args = {};
      }
      parameters = _.extend(args, {
        silent: true,
        success: function(model, response) {
          var cache, url;
          url = (typeof model.url === "function" ? model.url() : void 0) || model.url;
          cache = localStorage[url];
          if (!(cache != null) || !_.isEqual(model.toJSON(), JSON.parse(cache))) {
            return model.trigger('change');
          }
        }
      });
      return this.fetch(parameters);
    };
    Backbone.Collection.prototype.snatch = function(callback) {
      if (callback != null) {
        this.once('reset', callback);
      }
      return this.fetch({
        silent: true,
        success: function(collection, response) {
          var cache, url;
          url = (typeof collection.url === "function" ? collection.url() : void 0) || collection.url;
          cache = localStorage[url];
          if (!(cache != null) || !_.isEqual(collection.toJSON(), JSON.parse(cache))) {
            return collection.trigger('reset');
          }
        }
      });
    };
    return Backbone.View.prototype.assign = function(view, selector) {
      return view.setElement($(selector)).render();
    };
  });

}).call(this);
