// Generated by CoffeeScript 1.3.3
(function() {

  define([], function() {
    return function(method, model, options) {
      var data, url;
      if (typeof model.url === 'function') {
        url = model.url();
      } else {
        url = model.url;
      }
      switch (method) {
        case 'read':
          if (localStorage[url] != null) {
            console.log('cached: ', localStorage[url], Date.now());
            data = JSON.parse(localStorage[url]);
            model.reset(data);
          }
          return model.on('reset', function() {
            console.log('updated: ', model.toJSON(), Date.now());
            return localStorage[url] = JSON.stringify(model.toJSON());
          });
      }
    };
  });

}).call(this);
