// Generated by CoffeeScript 1.4.0
(function() {

  define(['backbone'], function(Backbone) {
    return function(method, model, options) {
      var data, url;
      if (typeof model.url === 'function') {
        url = model.url();
      } else {
        url = model.url;
      }
      switch (method) {
        case 'read':
          model.on('reset', function() {
            return localStorage[url] = JSON.stringify(model.toJSON());
          });
          model.on('change', function() {
            return localStorage[url] = JSON.stringify(model.toJSON());
          });
          if ((typeof localStorage !== "undefined" && localStorage !== null ? localStorage[url] : void 0) != null) {
            data = JSON.parse(localStorage[url]);
            if (model instanceof Backbone.Model) {
              model.set(data);
            }
            if (model instanceof Backbone.Collection) {
              return model.reset(data);
            }
          }
      }
    };
  });

}).call(this);
