// Generated by CoffeeScript 1.4.0
(function() {

  define(['hogan', 'text!../templates/home.html', 'text!../templates/layout.html', 'text!../templates/project/list.html', 'text!../templates/project/listitem.html'], function(Hogan, Home, Layout, ProjectList, ProjectListitem) {
    return {
      home: Hogan.compile(Home),
      layout: Hogan.compile(Layout),
      projectList: Hogan.compile(ProjectList),
      projectListitem: Hogan.compile(ProjectListitem)
    };
  });

}).call(this);
