// Generated by CoffeeScript 1.3.3
(function() {

  define(['views/account', 'views/api', 'views/entry', 'views/filebrowser', 'views/home', 'views/login', 'views/notfound', 'views/project/breadcrumb', 'views/project/list', 'views/project'], function(Account, Api, Entry, Filebrowser, Home, Login, Notfound, ProjectBreadcrumb, ProjectList, Project) {
    return {
      Account: Account,
      Api: Api,
      Entry: Entry,
      Filebrowser: Filebrowser,
      Home: Home,
      Login: Login,
      Notfound: Notfound,
      ProjectBreadcrumb: ProjectBreadcrumb,
      ProjectList: ProjectList,
      Project: Project
    };
  });

}).call(this);
