// Generated by CoffeeScript 1.4.0
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(['underscore', 'backbone'], function(_, Backbone) {
    var Files, ProjectLocale;
    ProjectLocale = (function(_super) {

      __extends(ProjectLocale, _super);

      function ProjectLocale() {
        return ProjectLocale.__super__.constructor.apply(this, arguments);
      }

      ProjectLocale.prototype.url = function() {
        return "/api/project_locales/?project_id=" + this.id;
      };

      ProjectLocale.prototype.parse = function(locales) {
        var trees;
        trees = {};
        _(locales).forEach(function(locale) {
          return trees[locale.tlocale.id] = {
            treeID: locale.id,
            localeName: locale.tlocale.name
          };
        });
        return trees;
      };

      return ProjectLocale;

    })(Backbone.Model);
    return Files = (function(_super) {

      __extends(Files, _super);

      function Files() {
        return Files.__super__.constructor.apply(this, arguments);
      }

      Files.prototype.url = function() {
        return "/api/po_files/?project_id=" + this.treeID;
      };

      Files.prototype.initialize = function(option) {
        var projectLocale,
          _this = this;
        this.projectID = option.projectID;
        this.localeID = option.localeID;
        projectLocale = new ProjectLocale({
          id: this.projectID
        });
        return projectLocale.on('sync', function() {
          _this.treeID = projectLocale.toJSON()[_this.localeID].treeID;
          _this.fetch();
          return _this.on('sync', function() {
            console.log('fuck');
            return console.log(_this.toJSON());
          });
        });
      };

      return Files;

    })(Backbone.Collection);
  });

}).call(this);
