// Generated by CoffeeScript 1.3.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(['underscore', 'backbone', '../models/file'], function(_, Backbone, Model) {
    var Collection;
    return Collection = (function(_super) {

      __extends(Collection, _super);

      function Collection() {
        return Collection.__super__.constructor.apply(this, arguments);
      }

      Collection.prototype.initialize = function(options) {
        return this.pid = options.pid;
      };

      Collection.prototype.model = Model;

      Collection.prototype.url = function() {
        return "projects/" + this.pid + "/files.json";
      };

      return Collection;

    })(Backbone.Collection);
  });

}).call(this);
