// Generated by CoffeeScript 1.4.0
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(['models/locale', 'underscore', 'backbone'], function(ModelLocale, _, Backbone) {
    var Collection;
    return Collection = (function(_super) {

      __extends(Collection, _super);

      function Collection() {
        return Collection.__super__.constructor.apply(this, arguments);
      }

      Collection.prototype.model = ModelLocale;

      Collection.prototype.url = function() {
        return "/api/project_locales/?project_id=" + this.id;
      };

      Collection.prototype.parse = function(data) {
        if (_.isArray(data)) {
          return data = data.map(function(locale) {
            return {
              id: locale.id,
              localeID: locale.locale.id,
              localeName: locale.locale.name
            };
          });
        } else {
          return data = [];
        }
      };

      return Collection;

    })(Backbone.Collection);
  });

}).call(this);
