// Generated by CoffeeScript 1.4.0
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(['models/locale', 'backbone'], function(ModelLocale, Backbone) {
    var Collection;
    return Collection = (function(_super) {

      __extends(Collection, _super);

      function Collection() {
        return Collection.__super__.constructor.apply(this, arguments);
      }

      Collection.prototype.model = ModelLocale;

      Collection.prototype.url = function() {
        return "/api/projects/" + this.id + "/locales";
      };

      Collection.prototype.parse = function(data) {
        return data.map(function(locale) {
          return {
            id: locale.id,
            localeID: locale.locale.id,
            localeName: locale.locale.name
          };
        });
      };

      return Collection;

    })(Backbone.Collection);
  });

}).call(this);
